---
from: <%= ENV['MAIL_FROM_ADDRESS'] %>
domain: <%= ENV['MAIL_DOMAIN'] %>
strategy: smtp
smtp_settings:
  address: <%= ENV['MAIL_SMTP_ADDRESS'] %>
  port: <%= ENV['MAIL_PORT'].to_s %>
  domain: <%= ENV['MAIL_DOMAIN'] %>
  user_name: <%= ENV['MAIL_USER_NAME'] %>
  password: <%= ENV['MAIL_PASSWORD'] %>
  authentication: plain
  enable_starttls_auto: false
