---
default: &default
  adapter: postgresql
  encoding: unicode
  charset: UTF8
  port: 5432
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  host: <%= ENV['POSTGRES_HOST'] %>
  
development:
  <<: *default
  database: squash_development

test:
  <<: *default
  database: squash_test

production:
  <<: *default
  database: squash_production
  pool: 30